# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ staging, main ]
  pull_request:
    branches: [ staging ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v1

      # Setup JDK version
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      # Execute clean build
      - name: Clean
        run: ./gradlew :app:clean

      # Execute lint validation
      - name: Assemble
        run: ./gradlew :app:assembleDebug

      # Execute unit tests
      - name: Unit Test
        run: ./gradlew :app:testDebugUnitTest
